# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Gradle Build

on:
  push:
    branches:
      - main
      - master
      - release
  pull_request:
    branches:
      - main
      - master
      - release

jobs:
  build:
    name: Build with ${{ matrix.distribution }} JDK ${{ matrix.jdk }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        jdk:
          - '17'
          - '18'
          - '19'
          - '20'
          - '21'
        distribution:
          - 'zulu'

    env:
      JAVA_PLATFORM_VERSION: ${{ matrix.jdk }}

    steps:
      # Check out sources
      - name: Fetch Sources
        uses: actions/checkout@v4
      - name: Fetch Sources of TweetwallFX-core projects
        uses: actions/checkout@v4
        with:
          path: .tweetwallFX-core/
          repository: TweetWallFX/TweetwallFX

      # Validate wrapper
      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1.1.0

      # Setup JDK environment for the next steps
      - name: Setup ${{ matrix.distribution }} JDK ${{ matrix.jdk }} for gradle
        uses: actions/setup-java@v3
        with:
          distribution: ${{ matrix.distribution }}
          java-version: ${{ matrix.jdk }}
          cache: gradle

      # Run assemble tasks
      - name: Run assemble tasks with toolchain JDK ${{ matrix.jdk }}
        uses: gradle/gradle-build-action@v2.8.1
        with:
          arguments: --no-daemon --refresh-dependencies --scan --warning-mode all assemble

#      # Run test tasks
#      - name: Run test tasks with toolchain JDK ${{ matrix.jdk }}
#        uses: gradle/gradle-build-action@v2.8.1
#        with:
#          arguments: --no-daemon --scan --warning-mode all test

      # Run check tasks
      - name: Run check tasks with toolchain JDK ${{ matrix.jdk }}
        uses: gradle/gradle-build-action@v2.8.1
        with:
          arguments: --no-daemon --scan --warning-mode all check -x test -x spotbugsTest
#          arguments: --no-daemon --scan --warning-mode all check

      # Archive test reports
      - name: Archive build logs
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.distribution }}-jdk${{ matrix.jdk }}-build-logs
          retention-days: 5
          path: |
            **/*.jfr
            **/hs_err_pid*.log
            **/build/reports/*
